### ISSUE TITLE
[BUG] PayloadTooBig error on plugin load/init

### ISSUE THREAD

**Issue by NeonDaniel** [mikejgray/neon-homeassistant-skill#50]
I noticed this bug preventing the enclosure service from starting on my Mark 2 today. I did recently add 4-5 devices so it may be related to the number of devices/entities I have.

```
2024-10-18 11:54:10.396 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:_connect:53 - DEBUG - {"type":"auth_required","ha_version":"2024.10.2"}
2024-10-18 11:54:10.405 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:authenticate:34 - DEBUG - {"type":"auth_ok","ha_version":"2024.10.2"}
2024-10-18 11:54:10.530 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:_connect:73 - ERROR - sent 1009 (message too big); no close frame received
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/framing.py", line 107, in read
    new_frame = extension.decode(new_frame, max_size=max_size)
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/extensions/permessage_deflate.py", line 133, in decode
    raise exceptions.PayloadTooBig(f"over size limit (? > {max_size} bytes)")
websockets.exceptions.PayloadTooBig: over size limit (? > 1048576 bytes)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/socketclient.py", line 59, in _connect
    await self.authenticate()
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/socketclient.py", line 40, in authenticate
    await self.listen()
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/socketclient.py", line 84, in listen
    message = await self.websocket.recv()
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 948, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1009 (message too big); no close frame received
2024-10-18 11:54:10.534 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:run:258 - INFO - self.loop.is_running=False
```

**Comment by mikejgray** [comment]
This is a bug in the PHAL plugin, so I'm going to copy it over there
