### ISSUE TITLE
`pip` installation from git failing

### ISSUE THREAD

**Issue by NeonDaniel** [mikejgray/neon-homeassistant-skill#8]
pip installation from PyPI appears to be missing the entrypoint for the skill to be loaded; when I tried installing from git, I see the following output.

```
(venv) neon@neon:~$ pip install git+https://github.com/mikejgray/neon-homeassistant-skill
Collecting git+https://github.com/mikejgray/neon-homeassistant-skill
  Cloning https://github.com/mikejgray/neon-homeassistant-skill to /tmp/pip-req-build-_4s0xxr3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/neon/venv/bin/python3.7 /home/neon/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpxw8c_4am
         cwd: /tmp/pip-req-build-_4s0xxr3
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/home/neon/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/neon/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/neon/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-kuvxf4pq/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
        builder = WheelBuilder(poetry)
      File "/tmp/pip-build-env-kuvxf4pq/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 59, in __init__
        super().__init__(poetry, executable=executable)
      File "/tmp/pip-build-env-kuvxf4pq/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/builder.py", line 87, in __init__
        includes=includes,
      File "/tmp/pip-build-env-kuvxf4pq/overlay/lib/python3.7/site-packages/poetry/core/masonry/utils/module.py", line 70, in __init__
        f"No file/folder found for package {name}"
    poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package neon-homeassistant-skill
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/neon/venv/bin/python3.7 /home/neon/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpxw8c_4am Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 23.0.1 is available.
You should consider upgrading via the '/home/neon/venv/bin/python3.7 -m pip install --upgrade pip' command.
```

**Comment by mikejgray** [comment]
Dev branch has a fix:

```shell
(venv) neon@neon:~$ pip install https://github.com/mikejgray/neon-homeassistant-skill/archive/dev.zip
Collecting https://github.com/mikejgray/neon-homeassistant-skill/archive/dev.zip
  Downloading https://github.com/mikejgray/neon-homeassistant-skill/archive/dev.zip
     \ 64.9 kB 909.9 kB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pfzy<0.4.0,>=0.3.4 in ./venv/lib/python3.7/site-packages (from neon-homeassistant-skill==0.0.8) (0.3.4)
Building wheels for collected packages: neon-homeassistant-skill
  Building wheel for neon-homeassistant-skill (pyproject.toml) ... done
  Created wheel for neon-homeassistant-skill: filename=neon_homeassistant_skill-0.0.8-py3-none-any.whl size=16682 sha256=54142b218a9a798d141e0f52e8c4e3747403b871506f94534f28acdccae746de
  Stored in directory: /tmp/pip-ephem-wheel-cache-c0e8i2wj/wheels/14/4b/3e/9c171e7f7c0e7c189130231aa3c2e2bcc1d992925092d2b345
Successfully built neon-homeassistant-skill
Installing collected packages: neon-homeassistant-skill
  Attempting uninstall: neon-homeassistant-skill
    Found existing installation: neon-homeassistant-skill 0.0.7
    Uninstalling neon-homeassistant-skill-0.0.7:
      Successfully uninstalled neon-homeassistant-skill-0.0.7
Successfully installed neon-homeassistant-skill-0.0.8
```

Once I've done some additional testing I'll link the PR to this issue to close it out.
